feat: Make android-studio optional
cachix/devenv pull request #1294
Opened 2024-06-22 04:24 UTC by k3yss

Fixes #1293

2024-06-22 11:39 UTC, domenkozar commented
Should it be then off in the example?

2024-06-22 12:03 UTC, k3yss commented
Disabled it! @domenkozar

2024-06-23 15:15 UTC, sandydoo requested changes

2024-06-23 15:15 UTC, sandydoo commented on src/modules/integrations/android.nix
> +    };
```suggestion
    android-studio.enable = lib.mkEnableOption "the installation of Android Studio";
```

2024-06-24 11:09 UTC, domenkozar commented
There are conflicts to be resolved

2024-06-24 11:17 UTC, k3yss commented
Resolved @domenkozar

2024-06-24 11:29 UTC, merged