fix: --upgrade-dep not available with python < 3.9
cachix/devenv pull request #1302
Opened 2024-06-26 11:11 UTC by k3yss

The `--upgrade-dep` flag was introduced in python version `3.9`, this PR disables the flag in case of python version lower than the version `3.9`

fixes #1289

2024-06-28 10:33 UTC, domenkozar requested changes

2024-06-28 10:33 UTC, domenkozar commented on src/modules/languages/python.nix
>            echo ${package.interpreter} -m venv --upgrade-deps "$VENV_PATH"
It would be better to just conditionalize the flag itself

2024-06-28 11:31 UTC, k3yss commented
Should be fine now @domenkozar

2024-06-28 19:08 UTC, k3yss commented
fixing tests

2024-06-29 14:55 UTC, domenkozar approved these changes

2024-06-30 14:55 UTC, merged