n8n: new service
cachix/devenv pull request #1630
Opened 2024-12-06 05:04 UTC by i-am-logger

having an issue #1628 will appriciate the help.

2024-12-10 22:40 UTC, i-am-logger commented
working, would appriciate a review

2024-12-31 04:13 UTC, sandydoo requested changes
Thanks, @i-am-logger. I've requested a bunch of minor changes, but otherwise looks good overall.

2024-12-31 04:13 UTC, sandydoo commented on src/modules/services/n8n.nix
> +        default = 5432;
The default in their docs is `5678`. `5432` is the default for postgres, so we should avoid using that.

```suggestion
        default = 5678;
```

2024-12-31 04:13 UTC, sandydoo commented on src/modules/services/n8n.nix
> +      N8N_CONFIG_FILES = "${configFile}";
This should work, no?

```suggestion
      WEBHOOK_URL = cfg.webhookUrl;
      N8N_CONFIG_FILES = configFile;
```

2024-12-31 04:13 UTC, sandydoo commented on src/modules/services/n8n.nix
> +      exec = "${pkgs.n8n}/bin/n8n";
It's nice to have a `package` option in the module to let people override the package used.

2024-12-31 04:13 UTC, sandydoo commented on tests/n8n/devenv.nix
> +{
To test that it launches, you can add a `.test.sh` script in this folder and `curl` a health endpoint of some kind. There are lots of examples of this in the repo.

2024-12-31 04:13 UTC, sandydoo commented on examples/n8n/devenv.nix
> +{ ... }:
The `n8n` can be removed in favor of the test.

2024-12-31 04:13 UTC, sandydoo commented on src/modules/services/n8n.nix
> +        type = lib.types.str;
If `null`, then the `WEBOOK_URL` env var won't be set at all, as long as you remove the quotes when setting the env var later.

```suggestion
        type = types.nullOr types.str;
```

2024-12-31 04:13 UTC, sandydoo commented on src/modules/services/n8n.nix
> +        default = "";
```suggestion
        default = null;
```

2024-12-31 04:16 UTC, sandydoo commented
@i-am-logger, I think quite a few of the requested changes are also applicable to your previous PR. I'll be happy to review it once updated.

2025-10-03 06:43 UTC, closed without merging