feat: add couchdb as a new service
cachix/devenv pull request #420
Opened 2023-02-19 21:35 UTC by MSBarbieri

2023-02-20 07:23 UTC, domenkozar requested changes

2023-02-20 07:23 UTC, domenkozar commented on src/modules/services/couchdb.nix
> +  imports = [
This import is not needed because this option is new, so it doesn't need renaming.

2023-02-20 07:23 UTC, domenkozar commented on src/modules/services/couchdb.nix
> +    enable = lib.mkEnableOption "Add CouchDB process script.";
```suggestion
    enable = lib.mkEnableOption "CouchDB process";
```

2023-02-20 18:32 UTC, shyim commented on src/modules/services/couchdb.nix
> +  );
What about we adopt this here https://github.com/NixOS/rfcs/blob/master/rfcs/0042-config-option.md

Basically we do:

```
settingsFormat = pkgs.formats.ini {};
configFile = settingsFormat.generate "couchdb.ini" cfg.settings;
```

...

```
settings = lib.mkOption {
      type = lib.types.submodule {
        freeformType = settingsFormat.type;

        options.couchdb.database_dir = lib.mkOption {
          type = lib.types.str;
          default = baseDir;
          description = lib.mdDoc ''
            Base Database dir
          '';
        };

        options.couchdb.uri_file = lib.mkOption {
          type = types.path;
          default = "${baseDir}/couchdb.uri";
          description = lib.mdDoc ''
            This file contains the full URI that can be used to access this
            instance of CouchDB. It is used to help discover the port CouchDB is
            running on (if it was set to 0 (e.g. automatically assigned any free
            one). This file should be writable and readable for the user that
            runs the CouchDB service (couchdb by default).
          '';
        };

        options.couchdb.view_index_dir = lib.mkOption {
          type = types.path;
          default = baseDir;
          description = lib.mdDoc ''
            Specifies location of CouchDB view index files. This location should
            be writable and readable for the user that runs the CouchDB service
            (couchdb by default).
          '';
        };

        options.couchdb.single_node = lib.mkOption {
          type = types.bool;
          default = true;
          description = lib.mdDoc ''
            Single node instance
          '';
        };
      };

      default = {};

      description = lib.mdDoc ''
        CouchDB configuration.
      '';
    };
```

then the user is able to configure anything inside the ini file 🤔 . also the options are specified in same position as the real config

2023-02-20 22:58 UTC, shyim commented on src/modules/services/couchdb.nix
> +    packages = [ cfg.package startScript ];
You should not add the startScript as package :thinking: or is there a specific reason. The process works also without adding it

2023-02-22 06:23 UTC, domenkozar commented on src/modules/services/couchdb.nix
> +    description = ''
This should be inside the `settings` option probably and not use xml but markdown for formatting. Then we're done :)

2023-02-22 17:33 UTC, shyim approved these changes

2023-02-23 02:57 UTC, merged