Add Meilisearch service
cachix/devenv pull request #626
Opened 2023-05-26 15:19 UTC by ankhers

An open-source, lightning-fast, and hyper-relevant search engine that fits effortlessly into your workflow.

2023-05-26 16:26 UTC, sandydoo requested changes
Thanks! We could use an example that simply enables the service to test this in our CI.

2023-05-26 16:50 UTC, sandydoo commented
`aarch64-linux` builds don't work right now. This'll be fixed in nixpkgs: https://github.com/NixOS/nixpkgs/pull/234258

2023-05-26 17:26 UTC, ankhers commented on src/modules/services/meilisearch.nix
> +    # TODO change this to LoadCredentials once possible
You are correct. I meant to remove it but forgot to after finishing.

2023-05-28 23:10 UTC, sandydoo commented
The x86_64 macOS test will be fixed once https://github.com/NixOS/nixpkgs/pull/234678 lands on unstable.

2023-05-30 07:22 UTC, domenkozar commented on src/modules/services/meilisearch.nix
> +
Nope.

2023-05-30 11:56 UTC, ankhers commented on src/modules/services/meilisearch.nix
> +
I just removed it.

2023-05-30 14:55 UTC, merged