Update yaml-options.md with clear instructions for adding packages that aren't part of Nix packages
cachix/devenv pull request #839
Opened 2023-10-09 14:50 UTC by matthiasdebernardini

Explicit instructions for what to do if you have an out of date dependency.

These would be clear for people new to Nix through devenv.

2023-10-10 10:45 UTC, domenkozar requested changes
Thanks a lot for this!

2023-10-10 10:45 UTC, domenkozar commented on docs/reference/yaml-options.md
> +### What to do if your package is out of date?
```suggestion
### What if a package is out of date?
```

2023-10-10 10:45 UTC, domenkozar commented on docs/reference/yaml-options.md
> +#### This is an example of a rust project that needs a new dependency
```suggestion
```

2023-10-10 10:45 UTC, domenkozar commented on docs/reference/yaml-options.md
> +  fenix:
Let's remove the fenix bit as it can be confusing and replace `taylor1791` with `$GH_USERNAME`, `master` with `mybranch`.

2023-10-10 10:45 UTC, domenkozar commented on docs/reference/yaml-options.md
> +    - Find the email of the maintainers, found on the Nix packages website
```suggestion
    - Open [nixpkgs repo](https://github.com/NixOS/nixpkgs) and press `t` to search for your package.
```

2023-10-10 10:45 UTC, domenkozar commented on docs/reference/yaml-options.md
> +    - Kindly ask them how you can help upgrade, either they will do it or you can do it yourself
```suggestion
    -  Try to update/change the package using [the nixpkgs contributing guide](https://nixos.org/manual/nixpkgs/stable/#chap-quick-start), optionally contacting the maintainer for help if you get stuck.
```

2023-10-10 10:45 UTC, domenkozar commented on docs/reference/yaml-options.md
> +    - Make a PR, get the URL of the patch
```suggestion
    - Make a PR and remember the branch name.
```

2023-10-10 10:45 UTC, domenkozar commented on docs/reference/yaml-options.md
> +    - It will take the form of 'github:$GH_USERNAME/nixpkgs/master'
```suggestion
Using the nixpkgs input in form of 'github:$GH_USERNAME/nixpkgs/master', edit `devenv.yaml`:
```

2023-10-10 10:45 UTC, domenkozar commented on docs/reference/yaml-options.md
> +    - Add it to your devenv.yaml like so
```suggestion
```

2023-10-24 22:12 UTC, matthiasdebernardini commented
Anything else I can do to get this merged?

2023-10-25 09:14 UTC, merged